services:
  - type: web
    name: devshowcase-api
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build && npx prisma db push
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
